---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels: 
    app.kubernetes.io/instance: audio-to-text-g1731931622418
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: audio-to-text-g1731931622418 
  name: audio-to-text-g1731931622418
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi