kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: audio-to-text-g1731931622418-imagestream-job-rolebinding
  namespace: redhat-ods-applications
subjects:
  - kind: ServiceAccount
    name: audio-to-text-g1731931622418-dsp-job
    namespace: rhdh-app
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: audio-to-text-g1731931622418-imagestream-job-role
